language: cpp
before_install: ./util/travis/before_install.sh
script: ./util/travis/script.sh
os: linux
dist: bionic
group: edge
notifications:
  email: false
matrix:
  fast_finish: true
  include:

    - env: CLANG_FORMAT=clang-format-8
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-format-8']

    - name: "Builtin Luacheck and Unit Tests"
      language: generic
      compiler: null
      os: linux
      addons:
        apt:
          packages:
          - luarocks
      before_install:
        - luarocks install --local luacheck
        - luarocks install --local busted
      script:
        - $HOME/.luarocks/bin/luacheck builtin
        - $HOME/.luarocks/bin/busted builtin

    - env: CLANG_TIDY=clang-tidy-8
      compiler: clang
      os: linux
      script: ./util/travis/clangtidy.sh
      addons:
        apt:
          packages: ['clang-tidy-8']

    - name: "MinGW cross-compiler (32-bit)"
      env: PLATFORM=Win32
      compiler: gcc
      os: linux

    - name: "MinGW cross-compiler (64-bit)"
      env: PLATFORM=Win64
      compiler: gcc
      os: linux

#    - env: PLATFORM=Unix
#      compiler: clang
#      os: osx
#      osx_image: xcode8

    - env: PLATFORM=Unix COMPILER=gcc-6
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-6', 'g++-6']

    - env: PLATFORM=Unix COMPILER=gcc-8
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-8', 'g++-8']

    - env: PLATFORM=Unix COMPILER=clang-3.9
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-3.9']

    - env: PLATFORM=Unix COMPILER=clang-9
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-9']

    - env: PLATFORM=Unix COMPILER=clang-9 FREETYPE=0
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-9']

    - env: PLATFORM=Unix COMPILER=clang-9 VALGRIND=1
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['valgrind', 'clang-9']
