name: lua_lint

# Lint on lua changes on builtin or if workflow changed
on:
  push:
    paths:
      - 'builtin/**.lua'
      - '.github/workflows/**.yml'
  pull_request:
    paths:
      - 'builtin/**.lua'
      - '.github/workflows/**.yml'

jobs:
  luacheck:
    name: "Builtin Luacheck and Unit Tests"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install luarocks
      run: |
        sudo apt-get install luarocks -qyy

    - name: Install luarocks tools
      run: |
        luarocks install --local luacheck
        luarocks install --local busted

    - name: Run checks
      run: |
        $HOME/.luarocks/bin/luacheck builtin
        $HOME/.luarocks/bin/busted builtin
